// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package database

import (
	"time"
)

type File struct {
	ID         int64
	FilePath   string
	MimeType   string
	Size       int64
	ModifiedAt time.Time
}
