// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package database

import (
	"database/sql"
	"time"
)

type File struct {
	ID         interface{}
	FilePath   string
	MimeType   string
	Size       sql.NullInt64
	ModifiedAt time.Time
}
