// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {database} from '../models';

export function GetAllFiles():Promise<Array<database.File>>;

export function OpenFileExplorer():Promise<void>;
