// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetAllFiles() {
  return window['go']['main']['App']['GetAllFiles']();
}

export function OpenFileExplorer() {
  return window['go']['main']['App']['OpenFileExplorer']();
}
